### ISSUE TITLE
Login with OAuth2 not appearing on front-end

### ISSUE THREAD

**Issue by zigomir** [discourse/discourse-oauth2-basic#2]
I did everything that readme says but then on page, when you click on login I don't get a button to login with this custom OAuth2 provider. I tried enabling google oauth and got button where I suspected.

Is there something I need to do about or is this plugin missing it?

More info:

I'm running in development with Vagrant and image that comes with discourse repo.
I could also found `oauth2_button_title` in script tag of page.

**Comment by eviltrout** [comment]
Can you double check the `oauth2_enabled` setting? It needs to be checked off.

**Comment by zigomir** [comment]
@eviltrout I had it all correct.

Enabling Custom OAuth2
![custom-oauth](https://cloud.githubusercontent.com/assets/957321/10304080/25371bb8-6c18-11e5-80b2-b1f9e484254f.png)

Enabling Google OAuth
![google-oauth](https://cloud.githubusercontent.com/assets/957321/10304081/25394d02-6c18-11e5-9e4d-bb9e74b8170c.png)

But then today I pulled latest master from Discourse again and now it works :)
