### ISSUE TITLE
Authorization Header Not Sent On Request to Token URL

### ISSUE THREAD

**Issue by seanzawi** [discourse/discourse-oauth2-basic#7]
First of all, thank you for making this plugin.  This has saved me a significant amount of time and works extremely well!

Unfortunately, it appears as though the plugin is not currently setting the Authorization Header when hitting the Token URL (optional according to the RFC: http://tools.ietf.org/html/rfc6749#page-16).  The SSO provider I'm working with requires this header to be set.  Theoretically the plugin already has the information needed (client-id & secret) and just needs to [optionally] send this header.

Thanks in advance!

**Comment by eviltrout** [comment]
Looks like it wouldn't harm anything to include this header always. I've added it in 7bc71b5378
